name: Continous deployment for golang api

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Ambiente a desplegar
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging

env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
  AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Build go-api
        run: go build -v -o go-api

      - name: Build .pem file
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > aws.pem
          echo "Pem file created"
          chmod 600 aws.pem
          echo "Pem file permissions set"

      - name: Deploy to production
        run: |
          echo "Deploying..."
          scp -o StrictHostKeyChecking=no -i aws.pem go-api ${{ env.AWS_EC2_USER }}@${{ env.AWS_EC2_HOST }}:~/go-api

      - name: Start api
        run: |
          echo "Starting api..."
          ssh -o StrictHostKeyChecking=no -i aws.pem ${{ env.AWS_EC2_USER }}@${{ env.AWS_EC2_HOST }} "./go-api"
          echo "Api started at: https://${{ env.AWS_EC2_HOST }}:3031"
